language: go

go:
  - 1.14.x

services: 
  - docker

script:
  - go test -v
  - go build -o ex04
  - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
  - docker build -f Dockerfile -t force0234/ex04:latest ./
  - GIT_SHA="$(git rev-parse --short HEAD"
  - docker tag force0234/ex04:latest force0234/ex04:$GIT_SHA